# Generated by Django 4.0 on 2022-01-27 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lider',
            fields=[
                ('nombre_completo', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Reunion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_reunion', models.CharField(max_length=100)),
                ('fecha_evento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('cedula', models.CharField(max_length=50, unique=True)),
                ('nombre_completo', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('telefono', models.CharField(max_length=50)),
                ('sexo', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Otro', 'Otro')], default='Masculino', max_length=50)),
                ('lider_referido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Asistencia.lider')),
            ],
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Asistencia.persona')),
                ('reunion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Asistencia.reunion')),
            ],
        ),
    ]
