# Generated by Django 4.0 on 2022-01-29 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Asistencia', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='sexo',
        ),
    ]
