# Generated by Django 4.0 on 2022-01-29 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asistencia', '0003_alter_reunion_descripcion_reunion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='reunion',
            field=models.CharField(default='EVENTO 29 ENERO 2022', max_length=100),
        ),
    ]
